/*
 * Backend for Docker containers ping info service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ContainerInfoField string

// List of ContainerInfoField
const (
	IP ContainerInfoField = "ip"
	LAST_PING ContainerInfoField = "lastPing"
	LAST_SUCCESS ContainerInfoField = "lastSuccess"
)
