/*
 * Backend for Docker containers ping info service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SortOrder string

// List of SortOrder
const (
	ASC SortOrder = "asc"
	DESC SortOrder = "desc"
)
