openapi: 3.0.0
info:
  title: Backend for Docker containers ping info service
  version: 0.1.0
servers:
- url: http://backend
  description: Backend
paths:
  /pings:
    get:
      summary: Получить информацию о пингах
      parameters:
      - $ref: '#/components/parameters/IP'
      - $ref: '#/components/parameters/OldestFirst'
      - $ref: '#/components/parameters/FilterSuccessful'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PingInfo'
        "400":
          description: Ошибка на стороне пользователя
        "500":
          description: Ошибка на стороне сервера
    put:
      summary: Загрузить информацию о пингах
      requestBody:
        description: Список результатов пинга
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PingInfo'
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Ошибка на стороне пользователя
        "500":
          description: Ошибка на стороне сервера
  /pings/aggregate:
    get:
      summary: Получить информацию о контейнерах и их последнем пинге
      parameters:
      - $ref: '#/components/parameters/ContainerSortProperty'
      - $ref: '#/components/parameters/SortOrder'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContainerInfo'
                x-content-type: application/json
        "400":
          description: Ошибка на стороне пользователя
        "500":
          description: Ошибка на стороне сервера
components:
  parameters:
    IP:
      in: query
      name: container_ip
      example: 127.0.0.1
      description: IP контейнера, для которого выдавать список пингов
      required: false
      style: form
      explode: true
      schema:
        type: string
    SortOrder:
      in: query
      name: order
      description: Порядок сортировки
      required: false
      style: form
      explode: true
      schema:
        type: string
        enum:
        - asc
        - desc
    Limit:
      in: query
      name: limit
      description: Максимальное количество выдаваемых результатов
      required: false
      style: form
      explode: true
      schema:
        type: integer
        minimum: 0
    Offset:
      in: query
      name: offset
      description: Количество результатов, которое необходимо пропустить
      required: false
      style: form
      explode: true
      schema:
        type: integer
        minimum: 0
    ContainerSortProperty:
      in: query
      name: sort
      description: Поле сортировки контейнеров
      required: false
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/ContainerSortProperty'
    OldestFirst:
      in: query
      name: oldest_first
      description: Сортировать начиная со старых записей
      required: false
      style: form
      explode: true
      schema:
        type: boolean
    FilterSuccessful:
      in: query
      name: filter
      required: false
      style: form
      explode: true
      description: Возвращать только успешные или неудавшиеся записи
      schema:
        type: boolean
  schemas:
    ContainerSortProperty:
      type: string
      enum:
      - ip
      - last_ping
      - last_success
    ContainerInfo:
      required: [ip]
      type: object
      properties:
        ip:
          type: string
        last_ping:
          type: integer
        last_success:
          type: integer
      example:
        ip: 127.0.0.1
        last_ping: 1739032217
        last_success: 1739032217
    PingInfo:
      type: object
      properties:
        ip:
          type: string
        timestamp:
          type: integer
        success:
          type: boolean
      example:
        ip: 127.0.0.1
        timestamp: 1739032217
        success: true
